export const States = [
    { title: "Alabama", id: "AL" },
    { title: "Alaska", id: "AK" },
    { title: "Arizona", id: "AZ" },
    { title: "Arkansas", id: "AR" },
    { title: "California", id: "CA" },
    { title: "Colorado", id: "CO" },
    { title: "Connecticut", id: "CT" },
    { title: "Delaware", id: "DE" },
    { title: "Florida", id: "FL" },
    { title: "Georgia", id: "GA" },
    { title: "Hawaii", id: "HI" },
    { title: "Idaho", id: "ID" },
    { title: "Illinois", id: "IL" },
    { title: "Indiana", id: "IN" },
    { title: "Iowa", id: "IA" },
    { title: "Kansas", id: "KS" },
    { title: "Kentucky", id: "KY" },
    { title: "Louisiana", id: "LA" },
    { title: "Maine", id: "ME" },
    { title: "Maryland", id: "MD" },
    { title: "Massachusetts", id: "MA" },
    { title: "Michigan", id: "MI" },
    { title: "Minnesota", id: "MN" },
    { title: "Mississippi", id: "MS" },
    { title: "Missouri", id: "MO" },
    { title: "Montana", id: "MT" },
    { title: "Nebraska", id: "NE" },
    { title: "Nevada", id: "NV" },
    { title: "New Hampshire", id: "NH" },
    { title: "New Jersey", id: "NJ" },
    { title: "New Mexico", id: "NM" },
    { title: "New York", id: "NY" },
    { title: "North Carolina", id: "NC" },
    { title: "North Dakota", id: "ND" },
    { title: "Ohio", id: "OH" },
    { title: "Oklahoma", id: "OK" },
    { title: "Oregon", id: "OR" },
    { title: "Pennsylvania", id: "PA" },
    { title: "Rhode Island", id: "RI" },
    { title: "South Carolina", id: "SC" },
    { title: "South Dakota", id: "SD" },
    { title: "Tennessee", id: "TN" },
    { title: "Texas", id: "TX" },
    { title: "Utah", id: "UT" },
    { title: "Vermont", id: "VT" },
    { title: "Virginia", id: "VA" },
    { title: "Washington", id: "WA" },
    { title: "West Virginia", id: "WV" },
    { title: "Wisconsin", id: "WI" },
    { title: "Wyoming", id: "WY" }
]